name: CI

on:
  pull_request:
    branches:
      - master
      - my-own-change-no-upstream
  push:
    branches:
      - master
      - my-own-change-no-upstream

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install latest stable Rust toolchain
        id: install-rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
          profile: default
      - uses: actions/cache@v3.0.1
        with:
          path: ~/.cargo/registry/index
          key: index-${{ runner.os }}-${{ github.run_number }}
          restore-keys: |
            index-${{ runner.os }}-
      - run: cargo generate-lockfile
      - uses: actions/cache@v3.0.1
        with:
          path: ~/.cargo/registry/cache
          key: registry-${{ runner.os }}-${{ steps.install-rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.lock') }}
      - run: cargo fetch
      - uses: actions/cache@v3.0.1
        with:
          path: target
          key: target-${{ github.job }}-${{ steps.install-rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.lock') }}
      - name: Test
        run: cargo test
