name: Enforce Rust formatting

on:
  push:
    branches: [ master, my-own-change-no-upstream ]
  pull_request:
    branches: [ master, my-own-change-no-upstream ]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sfackler/actions/rustup@master
      - uses: sfackler/actions/rustfmt@master
