name: Enforce Rust formatting

on:
  push:
    branches: [ master, my-own-change-no-upstream ]
  pull_request:
    branches: [ master, my-own-change-no-upstream ]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install latest stable Rust toolchain
        id: install-rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
          default: true
          profile: default
      - name: cargo fmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check
